export const PostsData = [
	{
		title: 'Renovare cladiri',
		description: 'As dori o renovare a cladirilor din zona de sud a orasului Brasov',
		user: 'Mihail Alexandru',
		city: '@brasov',
		status: 'Seen',
		image: 'https://www.ebihoreanul.ro/modules/news/files/prima-nufarul-oradea-12042021.jpg',
		upvotes: '10',
		downvotes: '3',
	},
	{
		title: 'Incalzire zona Decebal',
		description: 'Avem probleme cu caldura in zona Kaufland Iosia',
		user: 'Popescu Ion',
		city: '@oradea',
		status: 'Resolved',
		image: 'http://www.ebihoreanul.ro/modules/news/files/Bloc-ARED-Oradea.jpg',
		upvotes: '25',
		downvotes: '8',
	},
	{
		title: 'Denivelari drum centura',
		description: 'Am observat niste denivelari pe drumul de pe centura de la capatul orasului',
		user: 'Andrei Marcu',
		city: '@cluj-napoca',
		status: 'Sent',
		image: 'https://zcj.ro/images/db/1_3_191007_1571571652_09486.jpg',
		upvotes: '15',
		downvotes: '5',
	},
];
